version: "3.8"

services:
  website:
    container_name: anishmukherjee.info
    image: "anishmukherjee.info:latest"
    build:
      context: .
    volumes:
      - "./src:/website/src"
    ports:
      - 8080:80